### ISSUE TITLE
General enhancement: so many esri files bundle files in the root when building with ng build

### ISSUE THREAD

**Issue by wondie** [Esri/feedback-js-api-next#140] opened 2021-12-09 17:59 UTC
**Enhancement category**
Other

**Enhancement short summary**
So many ESRI library bundle files are created in the root of the build when building with ng build in angluar 12. 

**Enhancement description**
It would be good if these bundle files are kept in a sub-folder than the root of the build folder. 

**Severity**
Medium. It is difficult to navigate in the build folder as there are over 400 ESRI bundle files. No other libraries have this issue. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9709624/145449776-16ace3e9-82da-4f87-8ef3-6c535845704d.png)

**API version (check your console)**
 - Version: @arcgis/core@next (also tested in @arcgis/core@4.21.2 with the same issue)

**Additional context**
Angular 12.1.4, Webpack 5.58.1

**Comment by andygup** [comment] 2021-12-09 18:39
Hi @wondie the bundling output is controlled by Angular's default webpack configuration. This isn't controlled by the ArcGIS API for JavaScript.

Since Angular doesn't let you eject webpack anymore, you would need to create an Angular CLI builder that reads a custom webpack.config.js file: https://angular.io/guide/cli-builder.

**Comment by GeofoxCoding** [comment] 2021-12-17 14:20
Hello @andygup,

this is interesting. I'm facing the exact same thing at the moment. I create minimalistic angular workspace

ng new test

Inside app.component.ts I only import

```
import WebMap from "@arcgis/core/WebMap";
import MapView from "@arcgis/core/views/MapView";
```

and create a simple MapView.

I run ng serve and I get an output as shown above with hundreds of modules bundled into my app but I don't reference them anywhere. So why do they get bundled at all? I never had such a behaviour with any npm package.

Only the modules I reference should be bundled into vendor.js.

**Comment by odoe** [comment] 2021-12-17 15:25
@GeofoxCoding this is due to the dynamic loading of modules in the API `const module = await import('../someModule')`. WebMap for example could reference any number of modules depending on how the map was authored, so bundlers will chunk those modules in case they are needed. Some bundlers are more aggressive than others, but the number of files is expected.

**Comment by andygup** [comment] 2021-12-17 15:26
Hi @GeofoxCoding adding on to @odoe comment. That's expected behavior - `ng serve` is designed to serve and hot-swap modules as quickly as possible while you are building the app. It's not intended to provide a highly optimized output for production deployment.

**Comment by wondie** [comment] 2021-12-27 17:25
@andygup The same is true with `ng build`.

**Comment by andygup** [comment] 2022-03-22 21:32
@GeofoxCoding sorry I missed your response, I was on vacation at the time. I'm closing this issue since webpack is working as designed. 

Note, you can use an Angular Builder extension to tweak the webpack config and make adjustments to the module output. However, that is an Angular/webpack-specific issue and not something we troubleshoot. 

Here's an example link to a popular Builder library: https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack

**Closed by andygup** 2022-03-22 21:32 UTC
Labels: wontfix
