### ISSUE TITLE
CSS in Layerlist actions are wrong with toggle

### ISSUE THREAD

**Issue by TomGeograf** [Esri/feedback-js-api-next#154] opened 2022-03-18 08:27 UTC
**Describe the bug**
Toggle button is in wrong position, due to width of parrent element.

**To Reproduce**
1. Go to https://developers.arcgis.com/javascript/latest/sample-code/sandbox/?sample=widgets-layerlist-actions
2. Add ",type: "toggle" on line 102 

**Expected behavior**
Layerlist actions should have consistent width.

**Screenshots**
![image](https://user-images.githubusercontent.com/101738109/158964123-07241fe8-f539-4bac-b484-577848b5e0e9.png)

**Browser** 
 - Browser: ["Edge 99 on Windows 10"]
 
**What's your OS?**
 - OS: ["Windows 10* 64-bit"]
 - Device: ["Windows desktop PC"]

**API version (check your console)**
 - Version: [ArcGIS API for JavaScript 4.23-next [Date: 20220317, Revision: ff772db3]]

**Comment by ekenes** [comment] 2022-03-18 20:25
I'm not able to reproduce this issue. Can you paste a link to a codepen with the modified code? Thanks.

**Comment by TomGeograf** [comment] 2022-03-18 22:14
Try to download and open this zipped html code: [html.zip](https://github.com/Esri/feedback-js-api-next/files/8307906/html.zip)

![image](https://user-images.githubusercontent.com/101738109/159091474-f7d050db-15a4-4cd0-aa0a-dfd3da646c52.png)

Or copy and paste to your own html code:

<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1, maximum-scale=1,user-scalable=no"
    />

    <title>
      LayerList widget with actions | Sample | ArcGIS API for JavaScript 4.22
    </title>

    <style>
      html,
      body,
      #viewDiv {
        padding: 0;
        margin: 0;
        height: 100%;
        width: 100%;
        overflow: hidden;
      }
    </style>

    <link
      rel="stylesheet"
      href="https://js.arcgis.com/4.23/esri/themes/light/main.css"
    />
    <script src="https://js.arcgis.com/4.23/"></script>

    <script>
      require([
        "esri/Map",
        "esri/views/MapView",
        "esri/layers/GroupLayer",
        "esri/layers/MapImageLayer",
        "esri/widgets/LayerList",
        "esri/widgets/Slider"
      ], (Map, MapView, GroupLayer, MapImageLayer, LayerList, Slider) => {
        // Create layer showing sample data of the United States.
        const USALayer = new MapImageLayer({
          url: "http://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer",
          title: "US Sample Data"
        });

        // Create layer showing sample census data of the United States.
        // Set visibility to false so it's not visible on startup.

        const censusLayer = new MapImageLayer({
          url: "http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer",
          title: "US Sample Census",
          visible: false
        });

        // Create GroupLayer with the two MapImageLayers created above
        // as children layers.

        const demographicGroupLayer = new GroupLayer({
          title: "US Demographics",
          visible: true,
          visibilityMode: "exclusive",
          layers: [USALayer, censusLayer],
          opacity: 0.75
        });

        // Create a map and add the group layer to it

        const map = new Map({
          basemap: "gray-vector",
          layers: [demographicGroupLayer]
        });

        // Add the map to a MapView

        const view = new MapView({
          center: [-98.5795, 39.8282],
          zoom: 4,
          container: "viewDiv",
          map: map
        });

        // Creates actions in the LayerList.

        function defineActions(event) {
          // The event object contains an item property.
          // is is a ListItem referencing the associated layer
          // and other properties. You can control the visibility of the
          // item, its title, and actions using this object.

          const item = event.item;

          if (item.title === "US Demographics") {
            // An array of objects defining actions to place in the LayerList.
            // By making this array two-dimensional, you can separate similar
            // actions into separate groups with a breaking line.

            item.actionsSections = [
              [
                {
                  title: "Go to full extent",
                  className: "esri-icon-zoom-out-fixed",
                  id: "full-extent",
                  type: "toggle"
                },
                {
                  title: "Layer information",
                  className: "esri-icon-description",
                  id: "information"
                }
              ],
              [
                {
                  title: "Increase opacity",
                  className: "esri-icon-up",
                  id: "increase-opacity"
                },
                {
                  title: "Decrease opacity",
                  className: "esri-icon-down",
                  id: "decrease-opacity"
                }
              ]
            ];
          }

          // Adds a slider for updating a group layer's opacity
          if (item.children.length > 1 && item.parent) {
            const slider = new Slider({
              min: 0,
              max: 1,
              precision: 2,
              values: [1],
              visibleElements: {
                labels: true,
                rangeLabels: true
              }
            });

            item.panel = {
              content: slider,
              className: "esri-icon-sliders-horizontal",
              title: "Change layer opacity"
            };

            slider.on("thumb-drag", (event) => {
              const { value } = event;
              item.layer.opacity = value;
            });
          }
        }

        view.when(() => {
          // Create the LayerList widget with the associated actions
          // and add it to the top-right corner of the view.

          const layerList = new LayerList({
            view: view,
            // executes for each ListItem in the LayerList
            listItemCreatedFunction: defineActions
          });

          // Event listener that fires each time an action is triggered

          layerList.on("trigger-action", (event) => {
            // The layer visible in the view at the time of the trigger.
            const visibleLayer = USALayer.visible ? USALayer : censusLayer;

            // Capture the action id.
            const id = event.action.id;

            if (id === "full-extent") {
              // if the full-extent action is triggered then navigate
              // to the full extent of the visible layer
              view.goTo(visibleLayer.fullExtent).catch((error) => {
                if (error.name != "AbortError") {
                  console.error(error);
                }
              });
            } else if (id === "information") {
              // if the information action is triggered, then
              // open the item details page of the service layer
              window.open(visibleLayer.url);
            } else if (id === "increase-opacity") {
              // if the increase-opacity action is triggered, then
              // increase the opacity of the GroupLayer by 0.25

              if (demographicGroupLayer.opacity < 1) {
                demographicGroupLayer.opacity += 0.25;
              }
            } else if (id === "decrease-opacity") {
              // if the decrease-opacity action is triggered, then
              // decrease the opacity of the GroupLayer by 0.25

              if (demographicGroupLayer.opacity > 0) {
                demographicGroupLayer.opacity -= 0.25;
              }
            }
          });

          // Add widget to the top right corner of the view
          view.ui.add(layerList, "top-right");
        });
      });
    </script>
  </head>

  <body>
    <div id="viewDiv"></div>
  </body>
</html>

**Comment by ekenes** [comment] 2022-03-18 22:17
Got it. Thanks. We'll take a look at the issue.

**Comment by TomGeograf** [comment] 2022-03-18 22:21
Sure, I added a zipped file and code as a comment to my issue.

This issue is reproduced only in 4.23 version, you have to rewrite API version (from 4.22) in sample code.

Tom
________________________________

**Comment by annelfitz** [comment] 2022-03-22 17:00
This has been fixed on `/next`. Can you test again @TomGeograf ?

**Comment by TomGeograf** [comment] 2022-03-22 17:16
Sure, it´s ok now!

Maybe one more thing…

***@***.***

https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-LayerList-ListItem.html

If panel and actions are both defined, then those triggers are too much on right side. But it´s not something really horrible 😊

Thanks!

Od: Anne ***@***.***>
Odesláno:úterý 22. března 2022 18:00
Komu: ***@***.***>
Kopie: Tomáš ***@***.***>; ***@***.***>
Předmět: Re: [Esri/feedback-js-api-next] CSS in Layerlist actions are wrong with toggle (Issue #154)


This has been fixed on /next. Can you test again @TomGeograf<https://github.com/TomGeograf> ?

**Closed** 2022-03-22 20:25 UTC
Labels: bug, under consideration
