### ISSUE TITLE
Bug: GraphicMover doesn't work in 3D

### ISSUE THREAD

**Issue by LukashenkoEvgeniy** [Esri/feedback-js-api-next#40] opened 2020-04-06 14:25 UTC
**Describe the bug**
GraphicMover  doesn`t work as expected in 3D. method cloneMove in file drawUtils

**To Reproduce**
1. Go to https://jsfiddle.net/lukashenko/v4Lo6ypa/82/
2. Click on object in a map and try to drag. In 2D It work correctly.
3. Move to JS editor and change in 19 line   
```
const is2d = true;
```
to 
```
  const is2d = false;
```

3. Run app
4. Try repeat step 2.
5. See error in console
```
drawUtils.js:6 Uncaught TypeError: Cannot read property '0' of undefined
    at Object.m.cloneMove (drawUtils.js:6)
    at Object.d._dragHandler (GraphicMover.js:14)
    at GraphicMover.js:7
    at a._callback (dojo.js:1920)
    at b.a._handleEvent (dojo.js:1912)
    at Object.eventCallback (dojo.js:1908)
    at Object.f._doNewPropagation (dojo.js:1897)
    at Object.f._emitInputEvent (dojo.js:1896)
    at Object.f._emitInputEventFromSource (dojo.js:1896)
    at Object.f._onEventReceived (dojo.js:1892)
```

**Expected behavior**
Must drug symbol without error in 3d.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/17275749/78566920-914d2b00-7828-11ea-9903-af93d8f2bd49.png)

**Where problem**
MapView have fields
* transform
* inverseTransform

SceneView doesn' t have this properties and method cloneMove  throw exception because  transform and inverseTransform undefined.

If i add property value from 2D like

![image](https://user-images.githubusercontent.com/17275749/78567356-38ca5d80-7829-11ea-9950-73f609799474.png)

it will be work, but not correctly.

**Browser** 
 - Browser: "Chrome 80.0.3987.149 (Official Build) (64-bit) on Windows 10"
 
**What's your OS?**
 - OS:  Windows 10
 - Device: "Windows desktop PC"

**API version**
 - Version: ArcGIS API for JavaScript 4.14

**Video**

https://easyupload.io/7mrzyu
password: arcgis

**Comment by SaschaBrunnerCH** [comment] 2020-05-03 17:35
Hi @LukashenkoEvgeniy - thank you for reporting.
This is not a bug because `GraphicMover` is an undocumented feature and for `MapView` only. For undocumented features be aware that this may change without any advance notice.
Your requirment can be achieved by using [SketchViewModel](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch-SketchViewModel.html)

I updated your example with SketchViewModel and it works now in 2D and 3D:
https://jsfiddle.net/7aw84dsu/1/

![move_around_graphic](https://user-images.githubusercontent.com/46531184/80921190-2c2c1d00-8d75-11ea-9dda-aba237db8080.gif)

**Comment by SaschaBrunnerCH** [comment] 2020-05-15 11:39
@LukashenkoEvgeniy i close this one because it is not a bug and there is a way to do it.

**Closed** 2020-05-15 13:22 UTC
Labels: bug
