### ISSUE TITLE
Bug: Map Fails to Load in Production With Sample App

### ISSUE THREAD

**Issue by kevinkerr-cds** [Esri/feedback-js-api-next#131] opened 2021-08-11 13:13 UTC
**Describe the bug**
We went through a process to upgrade our Angular app and all of its packages only to discover our map did not load in our production configuration after migrating to Angular 12. We attempted to reproduce using the Esri sample app, and were able to cause the issue with both 4.20 and vnext. 

The error is: TypeError: Property description must be an object ...

**To Reproduce**
1. Download the Angular sample: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli
2. Update to vnext: npm install @arcgis/core@next
3. Run the app in production mode: ng serve --configuration=production
4. Or run it via http-server: 
ng build --prod
http-server dist/

**Expected behavior**
The map should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/45880051/129031836-0b8929e4-477f-417c-a564-93cb5b33c76c.png)

**Browser** 
 - Browser: Chrome 91
 
**What's your OS?**
 - OS: Windows 10* 64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - ArcGIS API for JavaScript 4.21.0-next.20210810 [Revision: d8d62578]]

**Additional context**
We observed the problem did not manifest when we disable build optimization via:

"optimization": false,

in angular.json

**Comment by andygup** [comment] 2021-08-11 14:48
Hi @kevinkerr-cds what version of node are you running?

**Comment by kevinkerr-cds** [comment] 2021-08-11 15:09
Hi @andygup thanks for your response. I am running Node v14.17.3 on my local system here, for reproducing this issue. A coworker is running v14.16.0.

**Comment by andygup** [comment] 2021-08-11 15:48
Okay, just double checking since Angular 12 has [specific node requirements](https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3#file-angular-cli-node-js-typescript-rxjs-compatiblity-matrix-csv-L35).

I was able to reproduce the issue. We'll take a closer look.

**Comment by andygup** [comment] 2021-08-11 22:49
@kevinkerr-cds quick follow-up, and thanks for pointing this issue out. For the moment, we recommend using Angular `12.1.x`. There were some surprisingly extensive changes to how they optimize at `12.2.x` and that's where things are breaking in production builds. The encouraging news is we tested with `13.0.0-next.0` and everything seemed to work okay (again). 

I'll also fix the Angular version used in the sample so that the sample works on initial install.

**Comment by kevinkerr-cds** [comment] 2021-08-14 14:03
@andygup Thanks for investigating, and for providing the workaround and test results with v13!

**Comment by andygup** [comment] 2021-11-08 21:01
Closing. The Angular sample in this repo has been updated to Angular 13 now that it has been released into production. I was not able to reproduce this issue using the updated sample: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli

**Closed by andygup** 2021-11-08 21:01 UTC
Labels: bug
