### ISSUE TITLE
Bug: Attribute driven rerender now slower?

### ISSUE THREAD

**Issue by mpayson** [Esri/feedback-js-api-next#4] opened 2019-09-20 20:08 UTC
**Describe the bug**
In 4.13, updating a simple feature layer renderer from one attribute-based definition to another seems slower relative to 4.12. Both log similar times when watching the 'updating' property, however visually 4.13 seems to take a second while 4.12 is almost instantaneous. 

Also, it looks like for both there's an intermediate render when switching, and this is more pronounced in 4.13.

**To Reproduce**
* Go here: https://codepen.io/mpayson/pen/GRKwLNX
* Click "Toggle Renderer" at least two times, this is with 4.12
* Switch the script tag to 4.13 and it should be noticeably slower

**Expected behavior**
Rerender data as fast as 4.12

**Browser (check https://whatismybrowser.com/)** 
 - Chrome 76 & Firefox 69
 
**What's your OS? (check https://whatsmyos.com):**
 - MacOS Mojave 10.14

**API version (check your console)**
 - Version: JavaScript 4.13-next.20190916 [Revision: f53393e5]

**Comment by mmgeorge** [comment] 2019-09-20 21:22
Thanks! Yes this does seem to be a performance regression. We'll take a look and get back to you. 

The intermediate states is an unfortunate limitation for now  that occurs when we have symbology and visualVariables changes, but we do have plans to improve this in the future. Symbology here changes because the ClassBreaksRenderer's field is changing. This currently requires us to reprocess the mesh for all the features on screen. Using a simple renderer in this case would be significantly faster: https://codepen.io/matt9222/pen/yLBGBbo?editors=1000

**Comment by mmgeorge** [comment] 2019-09-24 18:26
We currently have a fix for this in code review. There was a bug causing the update for rendering visual variable properties to get delayed until after the mesh was reprocessed. This should make the update appear to be faster. We also added some logic to prevent the intermediary state from showing in certain situations (something we still need to work on in future releases). 

4.12:
![before](https://user-images.githubusercontent.com/16738762/65539193-c7931080-debd-11e9-9bc0-fb20113c44b4.gif)

/next 
![next](https://user-images.githubusercontent.com/16738762/65539201-ccf05b00-debd-11e9-8ce3-6ab79fa0bf51.gif)

PR: 
![after](https://user-images.githubusercontent.com/16738762/65539214-d11c7880-debd-11e9-8faf-987c18b254e5.gif)

**Comment by ekenes** [comment] 2019-09-25 22:00
This has been installed. I was able to verify it on `next`. @mpayson Can you give this another try and let us know if you notice any other issues?

Closing.

**Closed by ekenes** 2019-09-25 22:00 UTC
Labels: bug

**Comment by mpayson** [comment] 2019-09-28 17:52
@ekenes missed your note, verified on my end as well--looks _awesome_. thanks!
