### ISSUE TITLE
Bug: Legend widget does not take `<LegendURL />` declarations for WMS sublayers into account

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/feedback-js-api-next#168] opened 2022-07-24 19:35 UTC
**Describe the bug**
The Legend widget does not take `<LegendURL />` declarations for WMS sublayers into account.

**To Reproduce**
1. Go to [https://codepen.io/sfrey/pen/PoRKPqB](https://codepen.io/sfrey/pen/PoRKPqB)
2. WMS Layer is added to the map with `legendEnabled` set to `true` and an explicit declared sublayer
3. Legend widget is added to the view
5. No legend graphic for declared WMS sublayer is displayed in the Legend widget

**Expected behavior**
When a WMS sublayer has a `<LegendURL />` tag defined and `legendEnabled` is set to true, the Legend widget should automatically render the in the capabilities declared legend graphic.

**Additional Context**
When an explicit URL is passed to the `legendUrl` parameter when declaring a sublayer, a legend graphic will be rendered.

**Comment by bsvensson** [comment] 2022-07-25 23:06
Hi @sebastianfrey , thank for letting us know. And thank you for adding a codepen :)

FYI - this repo is intended for "new" issues to the "next" version.

It seems like this issue can be reproduced with the released version (I tested 4.23 and 4.24 using your codepen).

**Comment by sebastianfrey** [comment] 2022-07-26 04:21
Hi @bsvensson,

You're welcome.

Got it. Next time I will fill such bug reports via Esri's support platform. However, from a developer perspective filling issues through your support platform is very cumbersome and time consuming, since it involves our local Esri distributer, which we than must convince, that the reported bug is really a bug. So I thought for this one, that I take a "short cut".  :-)

If desired, I fill an issue through your support platform.

**Comment by sebastianfrey** [comment] 2022-07-27 12:39
I have created a technical support case with number #03114053, which references this issue.

**Comment by annelfitz** [comment] 2022-09-01 20:34
Closing this issue, we will follow up once we have addressed the issue from support. Thanks @sebastianfrey!

**Closed** 2022-09-01 20:33 UTC
Labels: bug

**Comment by annelfitz** [comment] 2022-09-26 17:40
Hi @sebastianfrey - just following up on this issue - this is by design.

When assigning a value to `WMSLayer.sublayers` it essentially overwrites the layer's sublayers that are discovered from the service's get-capabilities response. Unless specified, all sublayer properties are set to their default property, for example the `title` is set to "Untitled layer".

The solution is to wait for the layer to load and "turn-off" undesired sublayers. This will ensure that all sublayer properties, like `legendUrl`, will be imported from the get-capabilities response.
```js
const wmsLayer = new WMSLayer({
  url: "https://sgx.geodatenzentrum.de/wms_basemapde?request=GetCapabilities",
  legendEnabled: true
});        

wmsLayer.load().then(() => {
  for (const sublayers of wmsLayer.allSublayers) {
    sublayers.visible = sublayers.name === "de_basemapde_web_raster_farbe"
  }
});
```
