### ISSUE TITLE
Regression: Domains in custom popups render coded value instead of description

### ISSUE THREAD

**Issue by roemhildtg** [Esri/feedback-js-api-next#145] opened 2022-01-27 20:44 UTC
**Describe the bug**
Custom popupTemplates that are created outside of the ootb means don't render the description values of fields with domains. For example, a coded value domain like:

| Coded Value | Description |
|--------------|-------------|
| HP  | High Pressure | 
| LP | Low Pressure | 

If a feature attribute is equal to "HP" - then the popup renderer should render "High Pressure" as it is the description of that domain. It instead renders "HP".

**To Reproduce**
https://codepen.io/roemhildtg/pen/XWdaRRb

1. Click on a feature - it will show the values for the fields with domains. 
2. You can change this to an earlier API version, IE 4.21 - and it does show the description - not values. 

**Expected behavior**
As this is a regression - the popup should show the description value, not the coded value. 

**Screenshots**

4.21 build 
https://gitlab.com/wsb-gis/datafi-projects/datafi/uploads/48d5d3d00553b07215a0f3991b0eeb58/image.png

next build:
https://gitlab.com/wsb-gis/datafi-projects/datafi/uploads/77cf5f740f3f45ae53a625ddd31df3e4/image.png

**Browser (check https://whatismybrowser.com/)** 
Chrome and Firefox tested
 
**What's your OS? (check https://whatsmyos.com):**
MacOS and Windows 10 tested

**API version (check your console)**
```
datafi@8.2.0 /Users/groemhildt/projects/datafi
└── @arcgis/core@4.23.0-next.20220127
```

**Additional context**
This issue has been reported to esri tech support as well. 
Re: Esri Case #02984733 - Regression in 4.22 PopupTemplate with Domains not populating Description

**Comment by andygup** [comment] 2022-01-27 23:49
Hi @roemhildtg - how come you are posting here in addition to opening the tech support ticket? Typically once the ticket is open we work directly with support to resolve issues. Also, this repo is for issues new to `next` or in this case `4.23`.

**Comment by steveoh** [comment] 2022-01-28 00:36
transparency?

**Comment by roemhildtg** [comment] 2022-01-28 17:48
HI @andygup  - thanks for taking a look. The issue occurs in JS API @ next - so I thought it would be relevant to here as well. If this is incorrect, I apologize for misunderstanding.

With this particular issue I was hoping to get it in front of a developer sooner rather than later. We are in the process of upgrading our flagship client application to the new API as we need to address some issues found in older versions. This app helps dozens of clients all of whom are Esri customers, and among them, hundreds of users so an issue like this has the potential to impact a lot of people and with it being such a critical feature (domain values in the popup) it will either need to be resolved via a workaround, fix, or risk derailing our entire upgrade project. Our clients will not accept having their domain values rendered incorrectly. 

Also, as @steveoh  mentioned - having the transparency in github is beneficial. My colleague recommended I post the issue in here just to get the issue in front of a developer sooner rather than later. Tech support (in my experience) often takes a week or more to identify/reproduce and can be months before I get any indication that the bug has been looked at by a developer. There's also no opportunity for a discussion with the developer - the issue is simply marked as "Not in product plan" or "Fixed" often with no way for me to test and verify that the fix actually resolves our issue. 

I'm really hoping that someone here could provide me with some sort of workaround so we can get our app upgraded, tested, and rolled out. Not having access to the source code makes this impossible for me to troubleshoot, and I can't use an earlier version as we are experiencing _other_ (different) issues in those that are fixed in 4.22/next.

**Comment by andygup** [comment] 2022-01-29 00:17
Hi @roemhildtg thanks for the additional context. Since this is a regression for 4.22 production release, tech support is the best place to get the bug into the queue for that initial triage. This repo is really for "new" features, fixes or issues that first appear in a `next` release. 

I've pinged @lboyd93 who works on Popups.

**Comment by lboyd93** [comment] 2022-01-29 00:58
Hi @roemhildtg - I will be following the Technical Support issue closely and once it's fully triaged to the product team, I will reach out through this issue once we have an update for you. 

I also wanted to note that once you get that BUG number from Technical Support, you can always escalate the defect with the use case/business justification that you provided above. That will be good information to have documented alongside the BUG that is submitted.

**Comment by odoe** [comment] 2022-01-29 12:37
The `returnUnformattedValues` for IdentifyParameters was changed at 4.22 to return `true` by default. You can set this to `false` in your app and you'll get the domain values, not the real values.
https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-IdentifyParameters.html#returnUnformattedValues

**Comment by odoe** [comment] 2022-01-29 12:52
Also, that snippet doesn't set the layer for the domain values, but since the `returnUnformattedValues` was false, you didn't notice.

```js
Object.assign(props.feature, {
  sourceLayer: layer, // has no impact
  sublayer, // has no impact
  popupTemplate: template,
});
```

But if you did this.

```js
Object.assign(props.feature, {
  layer: sublayer
  popupTemplate: template,
});
```

The popup would know the feature layer domain information and display properly.

You can also avoid setting the layer in 4.22 and pass the `sublayers: layers` in the parameters for Identify now and it will automatically assign the layer for the features.
https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-IdentifyParameters.html#sublayers

**Comment by roemhildtg** [comment] 2022-01-29 22:08
> The returnUnformattedValues for IdentifyParameters was changed at 4.22 to return true by default. You can set this to false in your app and you'll get the domain values, not the real values.

@odoe - thank you! this is the missing piece of information. Can you by chance show me where this change was documented? Just wondering if I missed that. 

> Also, that snippet doesn't set the layer for the domain values, but since the returnUnformattedValues was false, you didn't notice.

You're definitely correct, I didn't notice that this value was automatically passed in earlier versions of the API. I think it actually prefer it to be unformulated by default - so the db values are given for editing and other purposes. 

I'd like to add - after testing a few different tricks I found some interesting information:

As you mentioned, this works - and is by far the easiest solution to this:

> You can also avoid setting the layer manually in 4.22 and pass the sublayers: layers in the parameters for Identify now and it will automatically assign the layer for the features.

This eliminates the need to do any Object.assign on the returned features. Awesome. 

Alternatively - this worked, although according to the documentation I don't see how. Since layer should be an instance of [Layer](https://developers.arcgis.com/javascript/latest/api-reference/esri-Graphic.html#layer):

```js
            Object.assign(props.feature, {
              layer: sublayer,
              popupTemplate: template,
            });
```

In addition, this is undocumented, but works. In previous versions (4.21) this worked where sourceLayer was a MapImageLayer. Obviously this is undocumented and not supported but interesting. In 4.22 it appears sourceLayer can/should be a `SubLayer`. 

```js
            Object.assign(props.feature, {
              sourceLayer: sublayer,
              popupTemplate: template,
            });
```

This is the culprit that actually seems to break the domains:

```js
            Object.assign(props.feature, {
              layer: sublayer,
              sourceLayer: layer, // <--- when layer is a MapImageLayer - this breaks the domains in 4.22
              sublayer,
              popupTemplate: template,
            });
```

@lboyd93  thanks for following up on this - I realize now that this doesn't so much seem to be a popup issue but more of a "how do i tell the popup what the layer is" issue, if that makes sense. 

@andygup I'll keep that in in mind for next time. I don't want to waste anyone's time. I did attempt a lot of triage on my end before reaching out and not having a path forward was a bit exhausting at this point in our project. I do want to thank you and the team for the direct support, this conversation has hopefully given me enough information to hit our goal. I'll follow up with the tech support representative and hopefully close the loop on this.

**Comment by odoe** [comment] 2022-01-29 22:48
Those properties for setting the sourceLayer and sublayer are undocumented because they're used internally and not meant to be set by the user. No guarantee that they would or will always work.

**Comment by roemhildtg** [comment] 2022-02-02 16:20
FWIW I want to give a big thanks to you all for hopping into the ticket and providing these suggestions. While tech support may have been the recommended course of action here, issues like this are difficult for tech support to assist with. 

This isn't a super common workflow - although there is a public api for building custom popups, it seems that tech support is really not able to reproduce an issue unless its a problem with something they can reproduce in a super simple web map. That's the response I got today anyways. 

I'll let you decide when to close this - but I think my issue is now resolved. Thanks again.

**Comment by lboyd93** [comment] 2022-02-04 00:29
Thank you for the follow up, @roemhildtg!

The main thing Technical Support analysts are looking to do is narrow the issue down to try to figure out what could possibly be the issue (data, API bug, etc.) so they can triage to us accordingly. I'll connect with Technical Support since they should be able to assist with these types of things. 

I'll go ahead and close this out. Thanks again!

**Closed by lboyd93** 2022-02-04 00:29 UTC
Labels: bug
