### ISSUE TITLE
Bug: Getting console error messages when labeling feature layers

### ISSUE THREAD

**Issue by bbarnell** [Esri/feedback-js-api-next#71] opened 2020-09-30 15:49 UTC
**Describe the bug**
I am getting two errors when labeling client-side created feature layers:

"TypeError: Cannot read property '**readHydratedGeometry**' of null
    at Object.getGeometry (https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:556:365)
    at https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:288:181
    at https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:288:482
    at Array.filter (<anonymous>)
    at a.<anonymous> (https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:288:456)
    at d (https://js.arcgis.com/4.17/dojo/dojo-lite.js:47:190)
    at Object.next (https://js.arcgis.com/4.17/dojo/dojo-lite.js:45:492)
    at https://js.arcgis.com/4.17/dojo/dojo-lite.js:45:425
    at new Promise (<anonymous>)
    at Object.g [as __awaiter] (https://js.arcgis.com/4.17/dojo/dojo-lite.js:45:218)"

"TypeError: Cannot read property '**signal**' of undefined
    at https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:608:63
    at Array.forEach (<anonymous>)
    at a.<anonymous> (https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:607:493)
    at d (https://js.arcgis.com/4.17/dojo/dojo-lite.js:47:190)
    at Object.next (https://js.arcgis.com/4.17/dojo/dojo-lite.js:45:492)
    at g (https://js.arcgis.com/4.17/dojo/dojo-lite.js:45:275)"

**To Reproduce**
These are intermittent fatal error messages in the console window causing the labeling to stop working.  The "ReadHydratedGeometry" message is coming from the LayerView.QueryFeatures method.  Not sure where the "Signal" error is coming from. It says "Uncaught in promise".  When I turn off client side feature labeling, they stop happening.  Not sure how to reproduce other than by panning and zooming client side labels.

There are no issues in version 4.16 of the API other than printing them.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/2373699/94708434-99d37980-0312-11eb-8ceb-6412ddb58f41.jpg)

**Browser (check https://whatismybrowser.com/)** 
 - Browser: Chrome on Windows 10
 
**What's your OS? (check https://whatsmyos.com):**
 - OS: Windows 10  64-bit
 - Device: Windows desktop PC

**API version (check your console)**
 - Version: 4.17

**Comment by NoashX** [comment] 2020-09-30 17:21
Hi @bbarnell, thanks for reporting this issue. I tested this (I think I tested it properly based on your repro steps) and it works for me using `next` (no errors in console and labels display fine). Could you provide a simplified reproducible test case?

test-app
https://codepen.io/noash/pen/VwaONXP?editors=1000

test-app screenshot
![image](https://user-images.githubusercontent.com/2190813/94718432-989c4f80-0306-11eb-809a-6cfb94e45648.png)

**Comment by NoashX** [comment] 2020-10-05 17:18
Hi @bbarnell, could you provide a simplified reproducible test case? Or shall we close this issue for now? I am unable to reproduce the problem you described.

**Comment by NoashX** [comment] 2020-10-12 17:54
Hi @bbarnell, I am going to close this issue for now. Please feel free to write back here with a simplified reproducible test case if this issue still occurs for you.

**Closed by NoashX** 2020-10-12 17:54 UTC
Labels: bug
